sudo: false

language: python

cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "3.6"
install:
  - "pip install -U setuptools"
  - "pip install -r requirements/local.txt"
script:
  - "py.test --cov=./"
after_success:
  - "codecov"
