# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 20:17


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stein', '0006_auto_20151115_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineraltype',
            name='cleavage2',
            field=models.CharField(blank=True, choices=[('PE', 'Perfect'), ('LP', 'Less perfect'), ('GO', 'Good'),
                                                        ('DI', 'Distinct'), ('ID', 'Indistinct'), ('NO', 'None')],
                                   max_length=2, verbose_name='cleavage 2'),
        ),
        migrations.AddField(
            model_name='mineraltype',
            name='density',
            field=models.CharField(default=0, max_length=20, verbose_name='density'),
        ),
        migrations.AddField(
            model_name='mineraltype',
            name='fracture2',
            field=models.CharField(blank=True, choices=[('CF', 'Conchoidal'), ('EF', 'Earthy'), ('HF', 'Hackly'),
                                                        ('SF', 'Splintery'), ('UF', 'Uneven')], max_length=2,
                                   verbose_name='fracture 2'),
        ),
        migrations.AddField(
            model_name='mineraltype',
            name='lustre2',
            field=models.CharField(blank=True, choices=[('AM', 'Adamantine'), ('DL', 'Dull'), ('GR', 'Greasy'),
                                                        ('MT', 'Metallic'), ('PY', 'Pearly'), ('SL', 'Silky'),
                                                        ('SM', 'Submetallic'), ('VT', 'Vitreous'), ('WY', 'Waxy')],
                                   max_length=2, verbose_name='lustre 2'),
        ),
        migrations.AddField(
            model_name='mineraltype',
            name='other',
            field=models.CharField(blank=True, max_length=100, verbose_name='other'),
        ),
        migrations.AddField(
            model_name='mineraltype',
            name='resource_mindat',
            field=models.CharField(blank=True, max_length=100, verbose_name='MinDat ID'),
        ),
        migrations.AddField(
            model_name='mineraltype',
            name='resource_mineralienatlas',
            field=models.CharField(blank=True, max_length=100, verbose_name='MineralienAtlas ID'),
        ),
        migrations.AddField(
            model_name='mineraltype',
            name='systematics',
            field=models.CharField(
                choices=[('EL', 'Elements'), ('SF', 'Sulfides & Sulfosalts'), ('HG', 'Halogenides'),
                         ('OH', 'Oxides and Hydroxides'), ('CN', 'Carbonates and Nitrates'), ('BR', 'Borates'),
                         ('SL', 'Sulfates'), ('PV', 'Phosphates, Arsenates & Vanadates'),
                         ('SG', 'Silicates & Germanates'), ('OC', 'Organic Compounds')], default='EL', max_length=2,
                verbose_name='systematics'),
        ),
        migrations.AlterField(
            model_name='handpiece',
            name='current_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='current location'),
        ),
        migrations.AlterField(
            model_name='handpiece',
            name='finding_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='place of discovery'),
        ),
        migrations.AlterField(
            model_name='mineraltype',
            name='crystal_system',
            field=models.CharField(blank=True,
                                   choices=[('TC', 'Triclinic'), ('MC', 'Monoclinic'), ('OR', 'Orthorhombic'),
                                            ('TT', 'Tetragonal'), ('TR', 'Trigonal'), ('HG', 'Hexagonal'),
                                            ('CB', 'Cubic')], max_length=2, verbose_name='crystal system'),
        ),
        migrations.AlterField(
            model_name='mineraltype',
            name='minerals',
            field=models.CharField(blank=True, max_length=100, verbose_name='minerals'),
        ),
        migrations.AlterField(
            model_name='mineraltype',
            name='trivial_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='trivial name'),
        ),
        migrations.AlterField(
            model_name='mineraltype',
            name='variety',
            field=models.CharField(blank=True, max_length=100, verbose_name='variety'),
        ),
    ]
