# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stein', '0008_crystalsystem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mineraltype',
            old_name='cleavage',
            new_name='cleavage1',
        ),
        migrations.RenameField(
            model_name='mineraltype',
            old_name='fracture',
            new_name='fracture1',
        ),
        migrations.RenameField(
            model_name='mineraltype',
            old_name='lustre',
            new_name='lustre1',
        ),
    ]
