# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 14:34
from __future__ import unicode_literals

from django.db import migrations, models

import geomat.stein.fields


class Migration(migrations.Migration):
    dependencies = [
        ('stein', '0009_auto_20161008_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineraltype',
            name='fracture',
            field=geomat.stein.fields.ChoiceArrayField(base_field=models.CharField(
                choices=[(b'CF', 'Conchoidal'), (b'EF', 'Earthy'), (b'HF', 'Hackly'), (b'SF', 'Splintery'),
                         (b'UF', 'Uneven')], max_length=2), null=True, size=None, verbose_name='fracture'),
        ),
        migrations.AddField(
            model_name='mineraltype',
            name='cleavage',
            field=geomat.stein.fields.ChoiceArrayField(base_field=models.CharField(
                choices=[(b'PE', 'Perfect'), (b'LP', 'Less perfect'), (b'GO', 'Good'), (b'DI', 'Distinct'),
                         (b'ID', 'Indistinct'), (b'NO', 'None')], max_length=2), null=True, size=None,
                                                       verbose_name='cleavage'),
        ),
        migrations.AddField(
            model_name='mineraltype',
            name='lustre',
            field=geomat.stein.fields.ChoiceArrayField(base_field=models.CharField(
                choices=[(b'AM', 'Adamantine'), (b'DL', 'Dull'), (b'GR', 'Greasy'), (b'MT', 'Metallic'),
                         (b'PY', 'Pearly'), (b'SL', 'Silky'), (b'SM', 'Submetallic'), (b'VT', 'Vitreous'),
                         (b'WY', 'Waxy')], max_length=2), null=True, size=None, verbose_name='lustre'),
        ),
    ]
