# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 14:34


from django.db import migrations, models

import geomat.stein.fields


class Migration(migrations.Migration):
    dependencies = [
        ('stein', '0009_auto_20161008_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineraltype',
            name='fracture',
            field=geomat.stein.fields.ChoiceArrayField(base_field=models.CharField(
                choices=[('CF', 'Conchoidal'), ('EF', 'Earthy'), ('HF', 'Hackly'), ('SF', 'Splintery'),
                         ('UF', 'Uneven')], max_length=2), null=True, size=None, verbose_name='fracture'),
        ),
        migrations.AddField(
            model_name='mineraltype',
            name='cleavage',
            field=geomat.stein.fields.ChoiceArrayField(base_field=models.CharField(
                choices=[('PE', 'Perfect'), ('LP', 'Less perfect'), ('GO', 'Good'), ('DI', 'Distinct'),
                         ('ID', 'Indistinct'), ('NO', 'None')], max_length=2), null=True, size=None,
                                                       verbose_name='cleavage'),
        ),
        migrations.AddField(
            model_name='mineraltype',
            name='lustre',
            field=geomat.stein.fields.ChoiceArrayField(base_field=models.CharField(
                choices=[('AM', 'Adamantine'), ('DL', 'Dull'), ('GR', 'Greasy'), ('MT', 'Metallic'),
                         ('PY', 'Pearly'), ('SL', 'Silky'), ('SM', 'Submetallic'), ('VT', 'Vitreous'),
                         ('WY', 'Waxy')], max_length=2), null=True, size=None, verbose_name='lustre'),
        ),
    ]
