# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 14:59
from __future__ import unicode_literals

from django.db import migrations

"""
We have data inside the MineralType model that sits in unnecessary fields:
    1) fracture1 and fracture2
    2) cleavage1 and cleavage2
    3) lustre1 and lustre2

We want to combine the values of these fields into a new field, that accepts
several values as its input!
"""


def combine_fields(apps, schema_editor):
    MineralType = apps.get_model("stein", "MineralType")

    for mineral in MineralType.objects.all():
        # There may be a more elegant way/DRY in solving this, but this just works!

        # Fracture values
        fracture = [mineral.fracture1]

        if mineral.fracture2:
            fracture.append(mineral.fracture2)
        mineral.fracture = fracture

        # Cleavage values
        cleavage = [mineral.cleavage1]

        if mineral.cleavage2:
            cleavage.append(mineral.cleavage2)
        mineral.cleavage = cleavage

        # Lustre values
        lustre = [mineral.lustre1]

        if mineral.lustre2:
            lustre.append(mineral.lustre2)
        mineral.lustre = lustre

        mineral.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('stein', '0010_auto_20161008_1634'),
    ]

    operations = [
        migrations.RunPython(combine_fields)
    ]
