# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 14:59


from django.db import migrations

"""
We need to port data from the old 'crystal system' field into the new CrystalSystem model.
"""


def move_cristal_system(apps, schema_editor):
    MineralType = apps.get_model("stein", "MineralType")
    CrystalSystem = apps.get_model("stein", "CrystalSystem")

    for mineral in MineralType.objects.all():
        crystal = CrystalSystem(mineral_type=mineral, crystal_system=mineral.crystal_system)
        crystal.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('stein', '0012_auto_20161008_1721'),
    ]

    operations = [
        migrations.RunPython(move_cristal_system)
    ]
