# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stein', '0013_auto_20161008_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handpiece',
            name='resource_mindat',
        ),
        migrations.RemoveField(
            model_name='handpiece',
            name='resource_mineralienatlas',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='cleavage1',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='cleavage2',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='crystal_system',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='fracture1',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='fracture2',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='lustre1',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='lustre2',
        ),
    ]
