# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 12:45
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stein', '0015_auto_20161105_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, max_length=100, verbose_name='classification')),
                ('mineral_type',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stein.MineralType',
                                   verbose_name='mineral type')),
            ],
        ),
    ]
