# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0017_migrate_classification_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineraltype',
            name='classification1',
        ),
    ]
