# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0018_remove_mineraltype_classification1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineraltype',
            name='other',
            field=models.TextField(blank=True, max_length=100, verbose_name='comment'),
        ),
    ]
