# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:44


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stein', '0020_auto_20170119_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='classification',
            new_name='classification_name',
        ),
        migrations.AlterField(
            model_name='classification',
            name='mineral_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='classification', to='stein.MineralType', verbose_name='mineral type'),
        ),
        migrations.AlterField(
            model_name='crystalsystem',
            name='mineral_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='crystallsystem', to='stein.MineralType', verbose_name='mineral type'),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='handpiece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photograph',
                                    to='stein.Handpiece'),
        ),
    ]
