# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 19:21


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stein', '0021_auto_20170707_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='mineral_type', ),
        migrations.AddField(
            model_name='mineraltype',
            name='classification',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mineral_type',
                to='stein.Classification',
                verbose_name='classification'), ),
        migrations.AlterField(
            model_name='classification',
            name='classification_name',
            field=models.CharField(
                max_length=100, null=True, verbose_name='classification'), ),
    ]
