# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 19:29


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stein', '0022_auto_20170726_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'verbose_name': 'classification', 'verbose_name_plural': 'classifications'},
        ),
    ]
