# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0021_auto_20170707_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'verbose_name': 'Classification', 'verbose_name_plural': 'Classifications'},
        ),
        migrations.AlterModelOptions(
            name='crystalsystem',
            options={'verbose_name': 'Crystal System', 'verbose_name_plural': 'Crystal Systems'},
        ),
    ]
