# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0024_auto_20170727_1323'),
        ('stein', '0023_auto_20170726_2129'),
    ]

    operations = [
    ]
