# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0025_merge_20170818_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mineraltype',
            options={'verbose_name': 'Classification', 'verbose_name_plural': 'Classifications'},
        ),
    ]
