# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 08:37


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0025_merge_20170820_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystalsystem',
            name='crystal_system',
            field=models.CharField(
                blank=True,
                choices=[(b'TC', 'Triclinic'), (b'MC', 'Monoclinic'),
                         (b'OR', 'Orthorhombic'), (b'TT', 'Tetragonal'),
                         (b'TR', 'Trigonal'), (b'HG', 'Hexagonal'),
                         (b'CB', 'Cubic'), (b'AM', 'Amorph')],
                max_length=2,
                verbose_name='crystal system'), ),
        migrations.AlterField(
            model_name='mineraltype',
            name='classification',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mineral_type',
                to='stein.Classification',
                verbose_name='classification'), ),
    ]
