# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:42


from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0025_merge_20170820_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineraltype',
            name='image_file',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='crystalsystem',
            name='crystal_system',
            field=models.CharField(blank=True, choices=[('TC', 'Triclinic'), ('MC', 'Monoclinic'), ('OR', 'Orthorhombic'), ('TT', 'Tetragonal'), ('TR', 'Trigonal'), ('HG', 'Hexagonal'), ('CB', 'Cubic'), ('AM', 'Amorph')], max_length=2, verbose_name='crystal system'),
        ),
    ]
