# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0025_merge_20170820_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineraltype',
            name='image_file',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='crystalsystem',
            name='crystal_system',
            field=models.CharField(blank=True, choices=[(b'TC', 'Triclinic'), (b'MC', 'Monoclinic'), (b'OR', 'Orthorhombic'), (b'TT', 'Tetragonal'), (b'TR', 'Trigonal'), (b'HG', 'Hexagonal'), (b'CB', 'Cubic'), (b'AM', 'Amorph')], max_length=2, verbose_name='crystal system'),
        ),
    ]
