# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:49


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0026_auto_20171010_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mineraltype',
            old_name='image_file',
            new_name='images',
        ),
    ]
