# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0026_auto_20170818_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mineraltype',
            options={'verbose_name': 'mineral type', 'verbose_name_plural': 'mineral types'},
        ),
    ]
