# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 09:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0027_auto_20171010_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryEntry',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('header', models.CharField(max_length=200, null=True, verbose_name='header')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('examples', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='examples')),
            ],
            options={
                'verbose_name': 'Glossary Entry',
                'verbose_name_plural': 'Glossary Entries',
            },
        ),
    ]
