# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 13:37


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0032_auto_20171015_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineraltype',
            name='images',
        ),
    ]
