# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0033_remove_mineraltype_images'),
        ('stein', '0026_auto_20171009_1037'),
    ]

    operations = [
    ]
