# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 09:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import geomat.stein.fields
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0034_merge_20171018_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystalsystem',
            name='crystal_system',
            field=models.CharField(blank=True, choices=[('TC', 'Triclinic'), ('MC', 'Monoclinic'), ('OR', 'Orthorhombic'), ('TT', 'Tetragonal'), ('TR', 'Trigonal'), ('HG', 'Hexagonal'), ('CB', 'Cubic'), ('AM', 'Amorph')], max_length=2, verbose_name='crystal system'),
        ),
        migrations.AlterField(
            model_name='mineraltype',
            name='cleavage',
            field=geomat.stein.fields.ChoiceArrayField(base_field=models.CharField(choices=[('PE', 'Perfect'), ('LP', 'Less perfect'), ('GO', 'Good'), ('DI', 'Distinct'), ('ID', 'Indistinct'), ('NO', 'None')], max_length=2), null=True, size=None, verbose_name='cleavage'),
        ),
        migrations.AlterField(
            model_name='mineraltype',
            name='fracture',
            field=geomat.stein.fields.ChoiceArrayField(base_field=models.CharField(choices=[('CF', 'Conchoidal'), ('EF', 'Earthy'), ('HF', 'Hackly'), ('SF', 'Splintery'), ('UF', 'Uneven')], max_length=2), null=True, size=None, verbose_name='fracture'),
        ),
        migrations.AlterField(
            model_name='mineraltype',
            name='lustre',
            field=geomat.stein.fields.ChoiceArrayField(base_field=models.CharField(choices=[('AM', 'Adamantine'), ('DL', 'Dull'), ('GR', 'Greasy'), ('MT', 'Metallic'), ('PY', 'Pearly'), ('SL', 'Silky'), ('SM', 'Submetallic'), ('VT', 'Vitreous'), ('WY', 'Waxy')], max_length=2), null=True, size=None, verbose_name='lustre'),
        ),
        migrations.AlterField(
            model_name='mineraltype',
            name='systematics',
            field=models.CharField(choices=[('EL', 'Elements'), ('SF', 'Sulfides & Sulfosalts'), ('HG', 'Halogenides'), ('OH', 'Oxides and Hydroxides'), ('CN', 'Carbonates and Nitrates'), ('BR', 'Borates'), ('SL', 'Sulfates'), ('PV', 'Phosphates, Arsenates & Vanadates'), ('SG', 'Silicates & Germanates'), ('OC', 'Organic Compounds')], default='EL', max_length=2, verbose_name='systematics'),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='image_file',
            field=stdimage.models.StdImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='orientation',
            field=models.CharField(choices=[('T', 'Top'), ('B', 'Bottom'), ('S', 'Side')], max_length=1, verbose_name='orientation'),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='shot_type',
            field=models.CharField(choices=[('MI', 'Micro'), ('MA', 'Macro'), ('FE', 'Fisheye'), ('TL', 'Tele')], max_length=2, verbose_name='shot type'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='correct',
            field=models.BooleanField(help_text='Nothing yet.', verbose_name='correct'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='qtype',
            field=models.CharField(choices=[('SC', 'Single Choice'), ('MC', 'Multiple Choice'), ('DD', 'Drag and Drop'), ('RG', 'Ranking'), ('HS', 'Hotspot')], max_length=2, null=True, verbose_name='question type'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), help_text='If you want to add more than one tag, seperate them with commas.', null=True, size=None),
        ),
    ]
