# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0035_auto_20171025_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='FractureTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fracture', models.CharField(choices=[(b'CF', 'Conchoidal'), (b'EF', 'Earthy'), (b'HF', 'Hackly'), (b'SF', 'Splintery'), (b'UF', 'Uneven')], max_length=2, null=True, verbose_name='fracture')),
                ('coordinates', models.CharField(blank=True, max_length=20, null=True, verbose_name='coordinates')),
                ('mineral_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stein.MineralType', verbose_name='mineraltype')),
            ],
        ),
    ]
