# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 08:12
from __future__ import unicode_literals

from django.db import migrations


def transfer_fracture(apps, schema_editor):
    mineral_type = apps.get_model("stein", "MineralType")
    fracture = apps.get_model("stein", "FractureTwo")
    for m in mineral_type.objects.all():
        fractures= []
        for frac in m.fracture:
            fract = fracture.objects.create(fracture=frac)
            fractures.append(fract)
        m.fracturetwo.set(fractures)


def revert(apps, schema_editor):
    """We do not want to revert this. """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0037_auto_20171029_1254'),
    ]

    operations = [
    migrations.RunPython(transfer_fracture, revert)
    ]
