# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 13:39


from django.db import migrations, models
import geomat.stein.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0039_change_fractures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fracture',
            name='fracture',
            field=models.CharField(choices=[('CF', 'conchoidal'), ('EF', 'earthy'), ('HF', 'hackly'), ('SF', 'splintery'), ('UF', 'uneven')], max_length=2, null=True, verbose_name='fracture'),
        ),
        migrations.AlterField(
            model_name='mineraltype',
            name='cleavage',
            field=geomat.stein.fields.ChoiceArrayField(base_field=models.CharField(choices=[('PE', 'perfect'), ('LP', 'less perfect'), ('GO', 'good'), ('DI', 'distinct'), ('ID', 'indistinct'), ('NO', 'none')], max_length=2), null=True, size=None, verbose_name='cleavage'),
        ),
        migrations.AlterField(
            model_name='mineraltype',
            name='lustre',
            field=geomat.stein.fields.ChoiceArrayField(base_field=models.CharField(choices=[('AM', 'adamantine lustre'), ('DL', 'dull lustre'), ('GR', 'greasy lustre'), ('MT', 'metallic lustre'), ('PY', 'pearly lustre'), ('SL', 'silky lustre'), ('SM', 'submetallic lustre'), ('VT', 'vitreous lustre'), ('WY', 'waxy lustre')], max_length=2), null=True, size=None, verbose_name='lustre'),
        ),
    ]
