# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 16:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0040_auto_20171105_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='feedback_correct',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='feedback if answered correctly'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='feedback_incorrect',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='feedback if answered incorrectly'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='feedback_correct',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='feedback if answered correctly'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='feedback_incorrect',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='feedback if answered incorrectly'),
        ),
    ]
