# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:24


from django.db import migrations, models
import geomat.stein.fields


def transfer_back_fracture(apps, schema_editor):
    mineral_type = apps.get_model("stein", "MineralType")
    for mineral in mineral_type.objects.all():
        fractures =[]
        for fracture in mineral.fracture.all():
            fractures.append(fracture.fracture)
        mineral.fracture_two = fractures
        mineral.save()


def revert(apps, schema_editor):
    mineral_type = apps.get_model("stein", "MineralType")
    for mineral in mineral_type.objects.all():
        mineral.fracture_two = []
        mineral.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0041_auto_20171102_1755_squashed_0042_auto_20171105_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineraltype',
            name='fracture_two',
            field=geomat.stein.fields.ChoiceArrayField(base_field=models.CharField(choices=[(b'PE', 'perfect'), (b'LP', 'less perfect'), (b'GO', 'good'), (b'DI', 'distinct'), (b'ID', 'indistinct'), (b'NO', 'none')], max_length=2), null=True, size=None, verbose_name='fracture_two'),
        ),
        migrations.RunPython(transfer_back_fracture, revert)
    ]
