# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import geomat.stein.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0042_mineraltype_fracture_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fracture',
            name='mineral_type',
        ),
        migrations.RenameField(
            model_name='mineraltype',
            old_name='fracture_two',
            new_name='fracture'
        ),
        migrations.DeleteModel(
            name='Fracture',
        ),
    ]
