# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 20:58


from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0045_auto_20171112_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='image_file',
            field=stdimage.models.StdImageField(db_index=True, upload_to=b''),
        ),
    ]
