# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0046_auto_20171112_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossaryentry',
            name='examples',
        ),
    ]
