# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0048_auto_20171230_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossaryentry',
            options={'ordering': ('header',), 'verbose_name': 'Glossary Entry', 'verbose_name_plural': 'Glossary Entries'},
        ),
    ]
