# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0049_auto_20180116_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystalsystem',
            name='mineral_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crystal_system', to='stein.MineralType', verbose_name='mineral type'),
        ),
    ]
