# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0050_auto_20180123_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineraltype',
            name='split_systematics',
            field=models.CharField(blank=True, choices=[('SU', 'Sulfides'), ('SS', 'Sulfosalts'), ('CA', 'Carbonates'), ('NI', 'Nitrates'), ('PH', 'Phospates'), ('AR', 'Arsenates'), ('VA', 'Vanadates'), ('SI', 'Silicates'), ('GE', 'Germanates')], max_length=2, verbose_name='splitted systematics'),
        ),
        migrations.AddField(
            model_name='mineraltype',
            name='sub_systematics',
            field=models.CharField(blank=True, max_length=2, verbose_name='subsystematics'),
        ),
    ]
