# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 19:32
from __future__ import unicode_literals

from django.db import migrations, models


def fill_systematics(apps, schema_editor):

    MineralType = apps.get_model("stein", "MineralType")

    # first add all carboonates
    query = MineralType.objects.filter(chemical_formula__contains="CO_3")

    for mineral in query:
        mineral.split_systematics = 'CA'
        mineral.save()

    # next add Phosfates
    query = MineralType.objects.filter(chemical_formula__contains="PO_4")

    for mineral in query:
        mineral.split_systematics = 'PH'
        mineral.save()

    # next group silicates
    query = MineralType.objects.filter(chemical_formula__contains="Si_2O_7")

    for mineral in query:
        mineral.split_systematics = 'SI'
        mineral.sub_systematics = 'GS'
        mineral.save()

    # next double chain silicates
    query = MineralType.objects.filter(chemical_formula__contains="O_22")

    for mineral in query:
        mineral.split_systematics = 'SI'
        mineral.sub_systematics = 'DS'
        mineral.save()

    # next cyclo silicates
    query = MineralType.objects.filter(chemical_formula__contains="O_18")

    for mineral in query:
        mineral.split_sysematics = 'SI'
        mineral.sub_systematics = 'CC'
        mineral.save()

    # next phyllo silicates
    query = MineralType.objects.filter(chemical_formula__contains="O_10")

    for mineral in query:
        mineral.split_systematics = 'SI'
        mineral.sub_systematics = 'PS'
        mineral.save()


def revert(apps, schema_editor):

    MineralType = apps.get_model("stein", "MineralType")

    for mineral in MineralType.objects.all():
        mineral.split_sysematics = ""
        mineral.sub_systematics = ""
        mineral.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0051_auto_20180201_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineraltype',
            name='sub_systematics',
            field=models.CharField(blank=True, choices=[('IS', 'Island Silicates'), ('GS', 'Group Silicates'), ('CS', 'Chain Silicates'), ('DS', 'Double Chain Silicates'), ('CC', 'Cyclo Silicates'), ('PS', 'Phyllo Silicates'), ('FS', 'Framework Silicates')], max_length=2, verbose_name='subsystematics'),
        ),
        migrations.RunPython(fill_systematics, revert),
    ]
