# Generated by Django 2.0.2 on 2018-02-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0053_auto_20180203_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineraltype',
            name='classification',
        ),
    ]
