# Generated by Django 2.0.2 on 2018-04-24 07:45


import django.contrib.postgres.fields.ranges
from django.db import migrations

def transform_to_new_density(apps, schema_editor):
    MineralType = apps.get_model("stein", "MineralType")

    for mineral in MineralType.objects.all():
        mineral.new_density = tuple(float(x) for x in mineral.density.replace(",", ".").split("-"))
        mineral.save()

def revert(apps, schema_editor):

    MineralType = apps.get_model("stein", "MineralType")

    for mineral in MineralType.objects.all():
        new_density = mineral.new_denisty
        dens_string = "-".join((str(new_density.lower), str(new_density.upper))).replace(".", "-")
        mineral.density = dens_string
        mineral.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0055_delete_classification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineraltype',
            name='new_density',
            field=django.contrib.postgres.fields.ranges.FloatRangeField(blank=True, null=True),
        ),
        migrations.RunPython(transform_to_new_density, revert),
    ]
