# Generated by Django 2.0.3 on 2019-01-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0055_delete_classification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineraltype',
            name='other',
            field=models.TextField(blank=True, max_length=500, verbose_name='comment'),
        ),
    ]
