# Generated by Django 2.1.7 on 2019-04-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0060_remove_mineraltype_mohs_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=200, unique=True, verbose_name='node name')),
                ('info_text', models.TextField(blank=True, max_length=500)),
                ('is_top_level', models.BooleanField(default=False)),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stein.Photograph')),
                ('leaf_nodes', models.ManyToManyField(related_name='_treenode_leaf_nodes_+', to='stein.TreeNode')),
            ],
            options={
                'verbose_name': 'Tree Node',
                'verbose_name_plural': 'Tree Nodes',
            },
        ),
    ]
