# Generated by Django 2.1.7 on 2019-04-04 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0062_populate_treeNode_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treenode',
            options={'verbose_name': 'Tree Node', 'verbose_name_plural': 'Tree Nodes'},
        ),
        migrations.AddField(
            model_name='mineraltype',
            name='new_systematics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mineraltypes', to='stein.TreeNode'),
        ),
    ]
