# Generated by Django 2.1.7 on 2019-05-21 15:07

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0065_delete_old_systematics_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treenode',
            name='leaf_nodes',
        ),
        migrations.AddField(
            model_name='treenode',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treenode',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treenode',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaf_nodes', to='stein.TreeNode'),
        ),
        migrations.AddField(
            model_name='treenode',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treenode',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
