# Generated by Django 2.0.7 on 2019-05-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0066_auto_20190521_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='orientation',
            field=models.CharField(max_length=1, default="", verbose_name='orientation', choices=[('T', 'Top'), ('B', 'Bottom'), ('S', 'Side')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='photograph',
            name='shot_type',
            field=models.CharField(max_length=2, default="", verbose_name='shot type', choices=[('MI', 'Micro'), ('MA', 'Macro'), ('FE', 'Fisheye'), ('TL', 'Tele')]),
            preserve_default=True,
        ),
        migrations.RemoveField(
            model_name='photograph',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='photograph',
            name='shot_type',
        ),
        migrations.AddField(
            model_name='photograph',
            name='audio_file',
            field=models.FileField(null=True, blank=True, upload_to='audio', verbose_name='audio file'),
        ),
        migrations.AddField(
            model_name='photograph',
            name='description',
            field=models.TextField(default='', blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='photograph',
            name='orig_height',
            field=models.IntegerField(default=0, verbose_name='original height'),
        ),
        migrations.AddField(
            model_name='photograph',
            name='orig_width',
            field=models.IntegerField(default=0, verbose_name='original width'),
        ),
    ]
