# Generated by Django 2.0.7 on 2019-05-18 20:15

from django.db import migrations
import requests
from io import BytesIO
from PIL import Image


# Image files are served via cdn url
# therefore we first have to issue a
# http request and load the image to extract
# the image size.
def populate_image_size(apps, schema_editor):
    Photograph = apps.get_model("stein", "Photograph")

    for photo in Photograph.objects.all():
        response = None

        try:
            response = requests.get(photo.image_file.url)
        except requests.exceptions.MissingSchema:
            continue

        if response and response.status_code == 200:
            width, height = Image.open(BytesIO(response.content)).size
            photo.orig_width = width
            photo.orig_height = height
            photo.save()


def revert(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0067_rework_photograph_model'),
    ]

    operations = [
        migrations.RunPython(populate_image_size, revert)
    ]
