# Generated by Django 2.1.7 on 2019-05-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0068_populate_image_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='audio_duration',
            field=models.FloatField(default=0, verbose_name='duration of audio file'),
        ),
    ]
