# Generated by Django 2.2.1 on 2019-05-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0069_photograph_audio_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='overlay',
            field=models.TextField(blank=True, default='', verbose_name='overlay'),
        ),
        migrations.AddField(
            model_name='photograph',
            name='scale_factor',
            field=models.FloatField(default=0.0, blank=True, verbose_name='World to pixel scale'),
        ),
    ]
