# Generated by Django 2.2.1 on 2019-05-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stein', '0070_scale_factor_and_overlay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treenode',
            name='image',
        ),
    ]
